### ISSUE TITLE
Why is the ‘notification’ here set to nil? 

### ISSUE THREAD

**Issue by Asensiki** [SachK13/SKToast#4]
https://github.com/SachK13/SKToast/blob/89b317693e10943c077769ff424a20e375e9eaa0/SKToast/Classes/SKToastView.swift#L113

Why is the "Notification" set to nil here?
If nil, how to determine the position of the toastView when the keyboard pops up

**Comment by SachK13** [comment]
It is initially set to nil while initialisation of ToastView for the first time.
After that on Keyboard popup It receives Notification like .UIKeyboardDidShow and as per notification it changes its position. hope this will clear your doubt.
